version: "3.8"

services:
  # express:
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - redis

  database:
    image: mongo:latest
    container_name: mongoP2P
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ["--auth"]
    networks:
      - database


networks:
  database:
    driver: bridge

volumes:
  mongo-data:
    driver: local
